catalog/urls.py
from django.urls import path

from catalog.views import GoodItemListView, GoodItemCreateView, add, bay, success, cancel, webhook

app_name = 'catalog'

urlpatterns = [
    path('', GoodItemListView.as_view(), name='index'),
    # path('product/add/', GoodItemCreateView.as_view(), name='product-add'),
    path('product/add', add, name='product-add'),
    path('product/bay', bay, name='product-bay'),
    path('success', success, name='bay-success'),
    path('cancel', cancel, name='bay-cancel'),
    path('webhook', webhook, name='webhook'),
]

eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

# Create your models here.


class GoodItem(models.Model):
    created_at = models.DateTimeField(
        verbose_name='Дата добавления', 
        auto_created=True,
        auto_now_add=True
    )
    title = models.CharField(verbose_name='Название', max_length=255)
    price = models.PositiveIntegerField(verbose_name='Цена', default=0)
    vendor = models.CharField(verbose_name='Поставщик', max_length=255)
    unit_of_measure = models.CharField(verbose_name='Единица измерения', max_length=30)

    def __str__(self):
        return f'{self.title}, {self.vendor}'

    class Meta:
        verbose_name='Карточка товара'
        verbose_name_plural='Товары'

main/models.py
from django.db import models

# Create your models here.

catalog/forms.py
from django.forms import ModelForm

from catalog.models import GoodItem


class GoodItemForm(ModelForm):
    class Meta:
        model = GoodItem
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(GoodItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

catalog/views.py
import os

from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from django.template.loader import render_to_string
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from catalog.models import GoodItem
from catalog.forms import GoodItemForm
import stripe

stripe.api_key = os.getenv("API_KEY")

# Create your views here.

class GoodItemListView(ListView):
    model = GoodItem
    template_name = 'catalog/index.html'
    context_object_name = 'products'

    def get_queryset(self):
        return GoodItem.objects.all()

class GoodItemDetailView(DetailView):
    model = GoodItem

class GoodItemCreateView(CreateView):
    model = GoodItem
    fields = ['title', 'vendor', 'price', 'unit_of_measure']
    success_url = '/'

class GoodItemUpdateView(UpdateView):
    model = GoodItem

class GoodItemDeleteView(DeleteView):
    model = GoodItem

def add(request):
    data = dict()
    if request.method == 'POST':
        form = GoodItemForm(request.POST)
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            products = GoodItem.objects.all()
            data['products_html'] = render_to_string('catalog/list.html', {'products': products})
        else:
            data['form_html'] = render_to_string('catalog/gooditem_modal_form.html', {'form': form}, request=request)

    else:
        data['form_is_valid'] = False
        data['form_html'] = render_to_string('catalog/gooditem_modal_form.html', {'form': GoodItemForm()}, request=request)

    return JsonResponse(data)


# @csrf_exempt
def bay(request):
    HOST = "https://1c86-77-220-184-10.ngrok.io"
    m_data = {"transaction_id": "777"}

    try:
        checkout_session = stripe.checkout.Session.create(
            line_items=[
                {
                    # TODO: replace this with the `price` of the product you want to sell
                    'price_data': {
                        'currency': 'usd',
                        'product_data': {
                            'name': 'CDN service',
                        },
                        'unit_amount': 200,
                    },
                    'quantity': 1,
                },
            ],
            payment_method_types=[
              'card',
            #   'p24',
            ],
            mode='payment',
            success_url=HOST + '/success',
            cancel_url=HOST + '/cancel',
            payment_intent_data={"metadata": m_data},
        )

    except Exception as e:
        return str(e)
    
    print(checkout_session.url)
    return redirect(checkout_session.url, status=303)
    

def success(request):
    return render(request, "catalog/success.html")


def cancel(request):
    return render(request, "catalog/cancel.html")


@csrf_exempt
def webhook(request):
    endpoint_secret = os.getenv("STRIPE_WEBHOOK_SECRET")
    print(endpoint_secret)
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, endpoint_secret
        )
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)

    # Handle the event
    if event.type == 'payment_intent.succeeded':
        payment_intent = event.data.object  # contains a stripe.PaymentIntent
        print('PaymentIntent was successful!')
    elif event.type == 'payment_method.attached':
        payment_method = event.data.object  # contains a stripe.PaymentMethod
        print('PaymentMethod was attached to a Customer!')
    # ... handle other event types
    else:
        print('Unhandled event type {}'.format(event.type))
    return HttpResponse(status=200)

main/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <!-- Local CSS -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- Favicons -->
  <link rel="icon" href="{% static 'img/favicon.ico' %}">

  <title>E-SHOP!</title>
</head>

<body class="d-flex flex-column h-100">
  <header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="{% url 'catalog:index' %}"><b>E-SHOP</b></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'catalog:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
      </ul>
      <form class="form-inline mt-2 mt-md-0" id="header-search">
          <input class="form-control mr-sm-2" id="header-search-input" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
      </form>
      </div>
    </nav>
  </header>

  <!-- Begin page content -->
  <main role="main" class="flex-shrink-0">
    <div class="container mt-1">
      <br>
      {% block content %}{% endblock %}
      <!-- <button type="button" class="btn btn-outline-info btn-lg mb-4">Add product</button> -->
    </div>

  </main>

  <footer class="footer mt-auto py-3 bg-secondary">
    <div class="container">
      <span class="text-white">Place sticky footer content here.</span>
    </div>
  </footer>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  
  <!-- Local JavaScript -->
  {% block js %}{% endblock %}
  </body>
</html>

templates/catalog/cancel.html
{% extends "base.html" %}
{% load static%}


{% block content %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Cancel</h1>
  </div>
</div>

{% endblock %}

templates/catalog/gooditem_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section mt-5">
        <form action="{% url 'catalog:product-add' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Good item add/update</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Save</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/catalog/gooditem_modal_form.html
{% load crispy_forms_tags %}
<div class="content-section mt-5">
    <form action="{% url 'catalog:product-add' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            {{ form|crispy }}
        </fieldset>
    </form>
</div>

templates/catalog/index.html
{% extends "base.html" %}
{% load static%}
{% block content %}
  <br>
  <div class="mt-5 d-flex justify-content-between">
    <h1 class="">Catalog</h1>
    <button type="button" class="btn btn-outline-dark btn-lg mb-4" data-toggle="modal" data-url="{% url 'catalog:product-add' %}" data-target="#Modal">Add product</button>
  </div>
  <!-- Cards -->
  <div class="album">
    <div class="container">
      <div class="row" id="catalog">
        {% include "catalog/list.html" %}
      </div>
    </div>
  </div> 

  <!-- Modal product add window, shows in modal mode -->
  <div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Good item add/update</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {% include "catalog/gooditem_modal_form.html" %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <button type="button" id="add-button" class="btn btn-primary">Save</button>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block js %}
  <script src="{% static 'js/add_product.js' %}"></script>
{% endblock js %}

templates/catalog/list.html
{% load static%}
{% for product in products %}
    <div class="col-md-4 col-sm-6 p-0">
    <div class="card mr-2 mb-4 p-0 shadow rounded border border-info" style="width: 14rem;">
        <img src="{% static 'img/300x200.png' %}" class="card-img-top" alt="...">
        <div class="card-body">
        <h5 class="card-title">{{ product.title }}</h5>
        <p class="card-text">{{ product.vendor }}</p>
        <p class="card-text">Price: ${{ product.price }}</p>
        <form action="/product/bay" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-info">Bay</button>
        </form>
        </div>
    </div>
    </div>
{% endfor %}

templates/catalog/success.html
{% extends "base.html" %}
{% load static%}


{% block content %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Success</h1>
  </div>
</div>

{% endblock %}